spring:
  application:
    name: producer-spring-kafka
  cloud:
    stream:
      source: news
      kafka:
        binder:
          brokers: ${KAFKA_URL:localhost:9092}
      bindings:
        news-out-0:
          destination: news.json
          content-type: application/json
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 5

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate.on-profile: cloudkarafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: <BROKER>-01.srvs.cloudkafka.com:9094, <BROKER>-02.srvs.cloudkafka.com:9094, <BROKER>-03.srvs.cloudkafka.com:9094
          auto-create-topics: false
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
      bindings:
        news-out-0:
          destination: ${CLOUDKARAFKA_USERNAME}-events

server:
  port: 9200
